name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  DeployDev:
    name: Deploy to Dev 
    #if: github.event_name == 'pull_request'
    #needs: [Build]
    runs-on: dev-runner
    steps:
      #- uses: actions/checkout@v2
      - name: Deploy
        env:
          ACCESS_TOKEN: '${{ secrets.DEPLOYMENT }}'
        run: |
          git config --global user.name "shubham-rws"
          git pull https://${{secrets.ACCESS_TOKEN}}@github.com/shubham-rws/apps.git
    
  DeployQA:
    name: Deploy to QA 
    #if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: qa-runner
    steps:
      #- uses: actions/checkout@v2
      - name: Deploy
        env:
          ACCESS_TOKEN: '${{ secrets.DEPLOYMENT }}'
        run: |
          git config --global user.name "shubham-rws"
          git pull https://${{secrets.ACCESS_TOKEN}}@github.com/shubham-rws/apps.git
